export let sampleConfig = [
    {
    group:"Class A",
    "rows":[
        {
        "name":"A",
        "seats":[[
            {
                "number":1,
                "isBooked":true
            },
            {
                "number":2,
                "isBooked":true

            },
            {
                "number":3,
                "isBooked":false

            },
            {
                "number":4,
                "isBooked":false
            },{
                "number":5,
                "isBooked":false
            },
            {
                "number":6
            },
            {
                "number":7,
                "isBooked":true
            },
            {
                "number":8,
                "isBooked":true
            },{
                "number":9,
                "isBooked":true
            },
            {
                "number":10,
                "isBooked":true
            }],[]]
    },
    {
        "name":"B",
        "seats":[[
            {
                "number":1,
                "isBooked":true
            },
            {
                "number":2
            },
            {
                "number":3,
                "isBooked":true
            },
            {
                "number":4
            }],[{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7,
                "isBooked":true
            },
            {
                "number":8
            }]]
    },
    {
        "name":"C",
        "seats":[[
            {
                "number":1
            },
            {
                "number":2,
                "isBooked":true
            },
            {
                "number":3
            },
            {
                "number":4,
                "isBooked":true
            }],[{
                "number":5,
                "isBooked":true
            },
            {
                "number":6,
                "isBooked":true
            },
            {
                "number":7,
                "isBooked":true
            },
            {
                "number":8
            }]]
    },
    {
        "name":"D",
        "seats":[[
            {
                "number":1
            },
            {
                "number":2,
                "isBooked":true
            },
            {
                "number":3
            },
            {
                "number":4
            }],[{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8,
                "isBooked":true
            }]]
    },
    {
        "name":"E",
        "seats":[
            [],
            [{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4,
                "isBooked":true
            },{
                "number":1,
                "isBooked":true
            },
            {
                "number":2,
                "isBooked":true
            },
            {
                "number":3,
                "isBooked":true
            },
            {
                "number":4,
                "isBooked":true
            }]]
    },
]
},
{
    group:"Class B",
    "rows":[
        {
        "name":"F",
        "seats":[[
            {
                "number":1,
                "isBooked":true
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }],[{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            }]]
    },
    {
        "name":"G",
        "seats":[]
    },
    {
        "name":"H",
        "seats":[]
    },
    {
        "name":"I",
        "seats":[[
            {
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }],[{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            }]]
    },
    {
        "name":"J",
        "seats":[[
            {
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }],[{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            }]]
    },
    {
        "name":"K",
        "seats":[[
            {
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }],[{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            }]]
    },
    {
        "name":"L",
        "seats":[
            [],
            [{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }]]
    },
    {
        "name":"M",
        "seats":[
            [],
            [{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }]]
    },
    {
        "name":"M",
        "seats":[
            [],
            [{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }]]
    },
    {
        "name":"N",
        "seats":[
            [],
            [{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }]]
    },
    {
        "name":"O",
        "seats":[
            [],
            [{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }]]
    },
    {
        "name":"P",
        "seats":[
            [],
            [{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }]]
    },
    {
        "name":"Q",
        "seats":[
            [],
            [{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4
            }]]
    },
]
}, {
    group:"Class C",
    "rows":[
        {
        "name":"R",
        "seats":[[
            {
                "number":1,
                "isBooked":true
            },
            {
                "number":2,
                "isBooked":true

            },
            {
                "number":3,
                "isBooked":false

            },
            {
                "number":4,
                "isBooked":false
            },{
                "number":5,
                "isBooked":false
            },
            {
                "number":6
            },
            {
                "number":7,
                "isBooked":true
            },
            {
                "number":8,
                "isBooked":true
            },{
                "number":9,
                "isBooked":true
            },
            {
                "number":10,
                "isBooked":true
            }],[]]
    },
    {
        "name":"S",
        "seats":[[
            {
                "number":1,
                "isBooked":true
            },
            {
                "number":2
            },
            {
                "number":3,
                "isBooked":true
            },
            {
                "number":4
            }],[{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7,
                "isBooked":true
            },
            {
                "number":8
            }]]
    },
    {
        "name":"T",
        "seats":[[
            {
                "number":1
            },
            {
                "number":2,
                "isBooked":true
            },
            {
                "number":3
            },
            {
                "number":4,
                "isBooked":true
            }],[{
                "number":5,
                "isBooked":true
            },
            {
                "number":6,
                "isBooked":true
            },
            {
                "number":7,
                "isBooked":true
            },
            {
                "number":8
            }]]
    },
    {
        "name":"U",
        "seats":[[
            {
                "number":1
            },
            {
                "number":2,
                "isBooked":true
            },
            {
                "number":3
            },
            {
                "number":4
            }],[{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8,
                "isBooked":true
            }]]
    },
    {
        "name":"V",
        "seats":[
            [],
            [{
                "number":5
            },
            {
                "number":6
            },
            {
                "number":7
            },
            {
                "number":8
            },{
                "number":1
            },
            {
                "number":2
            },
            {
                "number":3
            },
            {
                "number":4,
                "isBooked":true
            },{
                "number":1,
                "isBooked":true
            },
            {
                "number":2,
                "isBooked":true
            },
            {
                "number":3,
                "isBooked":true
            },
            {
                "number":4,
                "isBooked":true
            }]]
    },
]
},]